#!/usr/bin/env bash

if [ ! -d "$HOME/.config-temp" ]; then
    mkdir ~/.config-temp
fi

ideaVersion="2022.2.3"

echo "Downloading WebStorm version $ideaVersion..."

sudo chown -R "$(whoami)" /usr/share
if wget -O ~/.config-temp/webstorm.tar.gz "https://download-cdn.jetbrains.com/webstorm/WebStorm-$ideaVersion.tar.gz"; then
    sudo rm -rf /usr/share/webstorm/
    mkdir /usr/share/webstorm/
    if tar -xzf ~/.config-temp/webstorm.tar.gz -C /usr/share/webstorm/ --strip-components 1; then
        sed -i "s/#\(\s\)*idea.plugins.path[^\n]*/idea.plugins.path=\${user.home}\/Development\/developer-utilities\/ideas-config\/webstorm/g"  '/usr/share/webstorm/bin/idea.properties'
        sed -i "s/#\(\s\)*idea.config.path[^\n]*/idea.config.path=\${user.home}\/Development\/developer-utilities\/ideas-config\/webstorm/g" '/usr/share/webstorm/bin/idea.properties'

        cp "web-storm/WebStorm.desktop" ~/.local/share/applications
        sudo cp "web-storm/webstorm" /usr/local/bin/
        sudo chmod +x /usr/local/bin/webstorm

        sudo chown -R "$(whoami)" /usr/share/webstorm
        echo "WebStorm installed successfully"
    fi
    rm ~/.config-temp/webstorm.tar.gz
fi
