#!/usr/bin/env bash

if [ ! -d "$HOME/.config-temp" ]; then
    mkdir ~/.config-temp
fi

rm -rf ~/.oh-my-zsh

sudo apt-get install fonts-powerline -y
sudo chsh -s /usr/bin/zsh

if wget -O ~/.config-temp/p10k.sh https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh; then
    sed -i 's/exec.*//g' "$HOME/.config-temp/p10k.sh"
    sh ~/.config-temp/p10k.sh
fi
