#!/usr/bin/env bash

sudo rm -rf ~/.oh-my-zsh/custom/themes/powerlevel10k
sudo rm -rf ~/.oh-my-zsh/plugins/zsh-autosuggestions
sudo rm -rf ~/.oh-my-zsh/plugins/zsh-syntax-highlighting
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/custom/themes/powerlevel10k
git clone https://github.com/zsh-users/zsh-autosuggestions.git ~/.oh-my-zsh/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/plugins/zsh-syntax-highlighting
cp ./oh-my-zsh/.p10k.zsh ~/
exec zsh -l
