#!/usr/bin/env bash

if [ ! -d "~/Development/" ]; then
    mkdir ~/Development/
fi

if [ ! -d "~/.config-temp" ]; then
    mkdir ~/.config-temp
fi

rm -rf ~/.oh-my-zsh

sudo apt-get install fonts-powerline -y
sudo chsh -s /usr/bin/zsh
sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"
