#!/usr/bin/env bash

cp .zshrc ~/

if [ ! -d "$HOME/Development/" ]; then
  mkdir ~/Development/
fi

if [ ! -d "$HOME/.config-temp" ]; then
  mkdir ~/.config-temp
fi

installer_run() {
  install_sh="./$1"
  if chmod +x "$install_sh"; then
    sh "$install_sh"
  fi
}

grep -E '^[^\s#]' <runner.conf | while IFS= read -r line; do
  installer_run "$line"
done

rm -Rf ~/.config-temp

if [ ! -d "$HOME/.config/dconf" ]; then
  echo "Creating dconf"
  mkdir ~/.config/dconf
fi

cp user ~/.config/dconf

exec zsh -l
