#!/usr/bin/env zsh

main() {
  cp .zshrc ~/

  if [ ! -d "$HOME/Development/" ]; then
    mkdir ~/Development/
  fi

  if [ ! -d "$HOME/.config-temp" ]; then
    mkdir ~/.config-temp
  fi

  installer_run() {
    install_sh="$1"
    if chmod +x "./$install_sh"; then
      ./"$install_sh"
      if [ $? -ne "0" ]; then
        echo "Failed to run command $install_sh"
      else
        echo "$install_sh successful executed"
      fi
    fi
  }

  grep -E '^[^\s#]' <runner.conf | while IFS= read -r line; do
    installer_run "$line"
  done

  echo
  echo
  echo "Setup completed, reboot system is required"
  sudo chsh -s /bin/bash
  exec zsh -l
}

rm -Rf "$HOME"/.config-temp
if [ ! -d "$HOME/.config/dconf" ]; then
  echo "Creating dconf"
  mkdir "$HOME"/.config/dconf
fi

cp ./user ~/.config/dconf

main

