#!/usr/bin/env bash

sudo apt update

sudo apt-get install -y curl ca-certificates gnupg lsb-release
sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev -y
sudo add-apt-repository ppa:git-core/ppa -y
sudo apt-get install fuse libfuse2 -y
sudo apt-get install build-essential file -y
sudo apt-get install xclip -y

sudo apt-get update

