#!/usr/bin/env bash

sudo apt update

sudo apt-get install -y zsh
sudo apt-get install -y ccrypt
sudo apt-get install -y curl ca-certificates gnupg lsb-release
sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev -y
sudo add-apt-repository ppa:git-core/ppa -y
sudo apt-get install fuse libfuse2 -y
sudo apt-get install build-essential file -y
sudo apt-get install xclip -y

export SDKMAN_DIR="/usr/local/sdkman" && curl -s "https://get.sdkman.io" | bash

# Set zsh as default
sudo chsh -s /usr/bin/zsh "$USER"

# Screen shot
sudo apt-get install flameshot -y

# Webcam view
sudo apt-get install guvcview -y

sudo update-locale LANG="en_US.UTF-8"
sudo update-locale LANGUAGE="en_US.UTF-8"
sudo update-locale LC_ALL="en_US.UTF-8"

sudo apt-get update

