#!/usr/bin/env bash

sudo apt update

sudo apt-get install -y zsh
sudo apt-get install -y ccrypt
sudo apt-get install libfuse2 -y

sudo apt-get install xclip -y

curl -s "https://get.sdkman.io" | bash
source "$HOME/.sdkman/bin/sdkman-init.sh"

# Set zsh as default
sudo chsh -s /usr/bin/zsh "$USER"

sudo apt-get update

