#!/usr/bin/env zsh

# https://jdk.java.net/archive/

if [ ! -d "$HOME/.config-temp" ]; then
  mkdir ~/.config-temp
fi

function installJdk() {
  JAVA_VERSION=$1

  JAVA_DIR="jdk-$JAVA_VERSION"
  sudo mkdir /usr/lib/jvm/"$JAVA_DIR"

  echo "Installing $JAVA_VERSION..."

  if wget -O ~/.config-temp/"$JAVA_VERSION".tar.gz $2; then
    if sudo tar -xzf ~/.config-temp/"$JAVA_VERSION".tar.gz -C /usr/lib/jvm/$JAVA_DIR/ --strip-components 1; then

      {
        echo
        echo "# Java configuration"
        echo export JAVA_HOME=\"/usr/lib/jvm/$JAVA_DIR\"
        echo export PATH="\"\$PATH:\$JAVA_HOME/bin\""
      } >>~/.zshrc

      echo "$JAVA_VERSION installed successfully"
    fi
    rm ~/.config-temp/"$JAVA_VERSION".tar.gz
  fi
}

installJdk openjdk-11.0.2 https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz
installJdk openjdk-17.0.2 https://download.java.net/java/GA/jdk17.0.2/dfd4a8d0985749f896bed50d7138ee7f/8/GPL/openjdk-17.0.2_linux-aarch64_bin.tar.gz
