#!/usr/bin/env zsh

if [ -z "$1" ]; then
  echo "Usage: $0 <jdk>"
  echo "Available jdk options"
  ls -a /usr/lib/jvm | grep "jdk-"
  exit 1
fi

sudo update-alternatives --install /usr/bin/java java "/usr/lib/jvm/$1"/bin/java 0
sudo update-alternatives --install /usr/bin/javac javac "/usr/lib/jvm/$1"/bin/javac 0

sudo update-alternatives --set java "/usr/lib/jvm/$1"/bin/java
sudo update-alternatives --set javac "/usr/lib/jvm/$1"/bin/javac

update-alternatives --list java
update-alternatives --list javac
