#!/usr/bin/env bash


if [ ! -d "$HOME/.config-temp" ]; then
    mkdir ~/.config-temp
fi

echo "Downloading Visual code..."
if curl -o ~/.config-temp/code.deb https://vscode.download.prss.microsoft.com/dbazure/download/stable/ddc367ed5c8936efe395cffeec279b04ffd7db78/code_1.98.2-1741788907_amd64.deb; then
  if sudo dpkg -i ~/.config-temp/code.deb;then
    echo "Visual code installed successfully"
  fi
  rm ~/.config-temp/code.deb
fi
