#!/usr/bin/env zsh

sudo apt update
sudo apt install --reinstall -y gdm3
sudo apt install --reinstall -y ubuntu-desktop
sudo apt install --reinstall -y gnome-shell

sudo dpkg-reconfigure gdm3

sudo systemctl restart gdm
