#!/usr/bin/env bash

rm -rf ~/download_temp/
mkdir ~/download_temp/

unzipJdk() {
  mkdir ~/download_temp/zulu-jdk-"$1"
  if tar -zxf ~/download_temp/zulu-jdk-"$1".tar.gz -C ~/download_temp/zulu-jdk-"$1" --strip-components 1; then
    sudo mv ~/download_temp/zulu-jdk-"$1"/zulu-"$1".jdk /Library/Java/JavaVirtualMachines/
    echo "JDK zulu-jdk-$1 installed"
  else
    echo "Failed to install JDK $1"
  fi
}

installJdk() {
  if curl -fsSL "$1" -o ~/download_temp/zulu-jdk-"$2".tar.gz; then
    unzipJdk "$2"
  fi
}

installJdk "https://cdn.azul.com/zulu/bin/zulu8.70.0.23-ca-jdk8.0.372-macosx_aarch64.tar.gz" 8

installJdk "https://cdn.azul.com/zulu/bin/zulu11.64.19-ca-jdk11.0.19-macosx_aarch64.tar.gz" 11

installJdk "https://cdn.azul.com/zulu/bin/zulu17.42.19-ca-jdk17.0.7-macosx_aarch64.tar.gz" 17

installJdk "https://cdn.azul.com/zulu/bin/zulu19.32.13-ca-jdk19.0.2-macosx_aarch64.tar.gz" 19

rm -rf ~/download_temp/
