#!/usr/bin/env bash

rm -rf ~/.oh-my-zsh
sudo apt update
sudo apt-get install curl -y
sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev -y
sudo add-apt-repository ppa:git-core/ppa -y
sudo apt update
sudo apt install git -y
sudo apt install xdg-desktop-portal-gnome -y
# https://github.com/Genymobile/scrcpy
sudo apt install scrcpy -y

sudo apt-get install fuse libfuse2 -y
sudo apt-get install build-essential file -y
sudo apt-get install xclip -y
sudo apt-get install zsh -y
sudo apt-get install fonts-powerline -y
sudo chsh -s /usr/bin/zsh
sudo apt-get install visualvm -y

sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"
