#!/usr/bin/env bash

if [ ! -d "$HOME/Development/" ]; then
  mkdir ~/Development/
fi

if [ ! -d "$HOME/.config-temp" ]; then
  mkdir ~/.config-temp
fi

installerRun() {
  chmod +x "$1"
  sh "$1"
}

grep -v '^ *#' < runner.conf | while IFS= read -r line
do
  installerRun "$line"
done

rm -Rf ~/.config-temp

if [ ! -d "$HOME/.config/dconf" ]; then
  echo "Creating dconf"
  mkdir ~/.config/dconf
fi

cp user ~/.config/dconf

sudo apt-get install zsh -y
cp .zshrc ~/
exec zsh -l
